package com.ulanzi.osrs;

import java.util.HashMap;
import java.util.Map;
import net.runelite.api.Skill;
import net.runelite.api.gameval.AnimationID;

/**
 * Animation ids follow RuneLite's idle notifier and mining plugin.
 * Prayer and magic are animation-only, because those skills also gain XP in combat.
 */
final class SkillActivities
{
	private static final Map<Integer, SkillActivity> BY_ANIMATION = new HashMap<>();

	static
	{
		bind(SkillActivity.WOODCUTTING,
			AnimationID.HUMAN_WOODCUTTING_BRONZE_AXE,
			AnimationID.HUMAN_WOODCUTTING_IRON_AXE,
			AnimationID.HUMAN_WOODCUTTING_STEEL_AXE,
			AnimationID.HUMAN_WOODCUTTING_BLACK_AXE,
			AnimationID.HUMAN_WOODCUTTING_MITHRIL_AXE,
			AnimationID.HUMAN_WOODCUTTING_ADAMANT_AXE,
			AnimationID.HUMAN_WOODCUTTING_RUNE_AXE,
			AnimationID.HUMAN_WOODCUTTING_GILDED_AXE,
			AnimationID.HUMAN_WOODCUTTING_DRAGON_AXE,
			AnimationID.HUMAN_WOODCUTTING_TRAILBLAZER_AXE_NO_INFERNAL,
			AnimationID.HUMAN_WOODCUTTING_INFERNAL_AXE,
			AnimationID.HUMAN_WOODCUTTING_3A_AXE,
			AnimationID.HUMAN_WOODCUTTING_CRYSTAL_AXE,
			AnimationID.HUMAN_OPENHEAVYCHEST,
			AnimationID.HUMAN_WOODCUTTING_TRAILBLAZER_RELOADED_AXE_NO_INFERNAL,
			AnimationID.HUMAN_WOODCUTTING_TRAILBLAZER_AXE,
			AnimationID.HUMAN_WOODCUTTING_TRAILBLAZER_RELOADED_AXE,
			AnimationID.FORESTRY_2H_AXE_CHOPPING_BRONZE,
			AnimationID.FORESTRY_2H_AXE_CHOPPING_IRON,
			AnimationID.FORESTRY_2H_AXE_CHOPPING_STEEL,
			AnimationID.FORESTRY_2H_AXE_CHOPPING_BLACK,
			AnimationID.FORESTRY_2H_AXE_CHOPPING_MITHRIL,
			AnimationID.FORESTRY_2H_AXE_CHOPPING_ADAMANT,
			AnimationID.FORESTRY_2H_AXE_CHOPPING_RUNE,
			AnimationID.FORESTRY_2H_AXE_CHOPPING_DRAGON,
			AnimationID.FORESTRY_2H_AXE_CHOPPING_CRYSTAL,
			AnimationID.FORESTRY_2H_AXE_CHOPPING_CRYSTAL_INACTIVE,
			AnimationID.FORESTRY_2H_AXE_CHOPPING_3A,
			AnimationID.HUMAN_CANOEING_CARVE_BRONZE_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_IRON_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_STEEL_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_BLACK_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_MITHRIL_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_ADAMANT_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_RUNE_AXE,
			AnimationID.BRUT_HUMAN_CANOEING_CARVE_GILDED_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_DRAGON_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_TRAILBLAZER_AXE_NO_INFERNAL,
			AnimationID.HUMAN_CANOEING_CARVE_INFERNAL_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_LEAGUE_TRAILBLAZER_AXE,
			AnimationID.BRUT_HUMAN_CANOEING_CARVE_3A_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_CRYSTAL_AXE,
			AnimationID.BRUT_HUMAN_CANOEING_CARVE_CRYSTAL_AXE,
			AnimationID.BRUT_HUMAN_CANOEING_CARVE_LEAGUE_TRAILBLAZER_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_BRONZE_2H_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_IRON_2H_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_STEEL_2H_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_BLACK_2H_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_MITHRIL_2H_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_ADAMANT_2H_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_RUNE_2H_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_DRAGON_2H_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_CRYSTAL_2H_AXE,
			AnimationID.HUMAN_CANOEING_CARVE_CRYSTAL_2H_AXE_INACTIVE,
			AnimationID.HUMAN_CANOEING_CARVE_3A_2H_AXE);

		bind(SkillActivity.FIREMAKING,
			AnimationID.HUMAN_CREATEFIRE,
			AnimationID.FORESTRY_CAMPFIRE_BURNING_ARCTIC_PINE_LOG,
			AnimationID.FORESTRY_CAMPFIRE_BURNING_BLISTERWOOD_LOGS,
			AnimationID.FORESTRY_CAMPFIRE_BURNING_LOGS,
			AnimationID.FORESTRY_CAMPFIRE_BURNING_MAGIC_LOGS,
			AnimationID.FORESTRY_CAMPFIRE_BURNING_MAHOGANY_LOGS,
			AnimationID.FORESTRY_CAMPFIRE_BURNING_MAPLE_LOGS,
			AnimationID.FORESTRY_CAMPFIRE_BURNING_OAK_LOGS,
			AnimationID.FORESTRY_CAMPFIRE_BURNING_REDWOOD_LOGS,
			AnimationID.FORESTRY_CAMPFIRE_BURNING_TEAK_LOGS,
			AnimationID.FORESTRY_CAMPFIRE_BURNING_WILLOW_LOGS,
			AnimationID.FORESTRY_CAMPFIRE_BURNING_YEW_LOGS,
			AnimationID.BRUT_PLAYER_FIREMAKING_AIDE_SHORTBOW,
			AnimationID.BRUT_PLAYER_FIREMAKING_SHORTBOW,
			AnimationID.BRUT_PLAYER_FIREMAKING_OAK_SHORTBOW,
			AnimationID.BRUT_PLAYER_FIREMAKING_WILLOW_SHORTBOW,
			AnimationID.BRUT_PLAYER_FIREMAKING_MAPLE_SHORTBOW,
			AnimationID.BRUT_PLAYER_FIREMAKING_YEW_SHORTBOW,
			AnimationID.BRUT_PLAYER_FIREMAKING_MAGIC_SHORTBOW,
			AnimationID.BRUT_PLAYER_FIREMAKING_DAGANOTH_BOW);

		bind(SkillActivity.COOKING,
			AnimationID.HUMAN_FIRECOOKING,
			AnimationID.HUMAN_COOKING,
			AnimationID.HUMAN_MAKE_WINE,
			AnimationID.HUMAN_CUT_FOOD,
			AnimationID.MILKIT,
			AnimationID.PLAYER_CHURNS_MILK_SHORT,
			AnimationID.PLAYER_CHURNS_MILK_MEDIUM,
			AnimationID.PLAYER_CHURNS_MILK_LONG);

		bind(SkillActivity.CRAFTING,
			AnimationID.HUMAN_OPALCUTTING,
			AnimationID.HUMAN_JADECUTTING,
			AnimationID.HUMAN_REDTOPAZCUTTING,
			AnimationID.HUMAN_SAPPHIRECUTTING,
			AnimationID.HUMAN_EMERALDCUTTING,
			AnimationID.HUMAN_RUBYCUTTING,
			AnimationID.HUMAN_DIAMONDCUTTING,
			AnimationID.HUMAN_DRAGONSTONECUTTING,
			AnimationID.HUMAN_ONYXCUTTING,
			AnimationID.HUMAN_AMETHYSTCUTTING,
			AnimationID.HUMAN_GLASSBLOWING,
			AnimationID.HUMAN_SPINNINGWHEEL_60,
			AnimationID.HUMAN_SPINNINGWHEEL_90,
			AnimationID.FARMING_USELOOM,
			AnimationID.HUMAN_BATTLESTAFF_CRAFTING,
			AnimationID.HUMAN_LEATHER_CRAFTING,
			AnimationID.HUMAN_POTTERYWHEEL,
			AnimationID.HUMAN_CUTTING_RESTART,
			AnimationID.HUMAN_GOLEM_CHISEL_END,
			AnimationID.HUMAN_FILLBUCKET_SANDPIT);

		bind(SkillActivity.FLETCHING,
			AnimationID.HUMAN_FLETCHING,
			AnimationID.XBOWS_FLETCHING_WOOD_BRONZE,
			AnimationID.XBOWS_FLETCHING_OAK_BLURITE,
			AnimationID.XBOWS_FLETCHING_WILLOW_IRON,
			AnimationID.XBOWS_FLETCHING_TEAK_STEEL,
			AnimationID.XBOWS_FLETCHING_MAPLE_MITHRIL,
			AnimationID.XBOWS_FLETCHING_MAHOGANY_ADAMANTITE,
			AnimationID.XBOWS_FLETCHING_YEW_RUNITE,
			AnimationID.XBOWS_FLETCHING_YEW_DRAGON,
			AnimationID.STRINGING_SHORTBOW,
			AnimationID.STRINGING_OAK_SHORTBOW,
			AnimationID.STRINGING_WILLOW_SHORTBOW,
			AnimationID.STRINGING_MAPLE_SHORTBOW,
			AnimationID.STRINGING_YEW_SHORTBOW,
			AnimationID.STRINGING_MAGIC_SHORTBOW,
			AnimationID.STRINGING_LONGBOW,
			AnimationID.STRINGING_OAK_LONGBOW,
			AnimationID.STRINGING_WILLOW_LONGBOW,
			AnimationID.STRINGING_MAPLE_LONGBOW,
			AnimationID.STRINGING_YEW_LONGBOW,
			AnimationID.STRINGING_MAGIC_LONGBOW,
			AnimationID.HUMAN_FLETCHING_ADD_FEATHER,
			AnimationID.HUMAN_FLETCHING_ADD_ARROW_TIPS,
			AnimationID.HUMAN_FLETCHING_ADD_BOLT_TIPS_BRONZE,
			AnimationID.HUMAN_FLETCHING_ADD_BOLT_TIPS_IRON,
			AnimationID.HUMAN_FLETCHING_ADD_BOLT_TIPS_BLURITE,
			AnimationID.HUMAN_FLETCHING_ADD_BOLT_TIPS_STEEL,
			AnimationID.HUMAN_FLETCHING_ADD_BOLT_TIPS_MITHRIL,
			AnimationID.HUMAN_FLETCHING_ADD_BOLT_TIPS_ADAMANT,
			AnimationID.HUMAN_FLETCHING_ADD_BOLT_TIPS_RUNE,
			AnimationID.HUMAN_FLETCHING_ADD_BOLT_TIPS_DRAGON,
			AnimationID.HUMAN_FLETCHING_HUNTINGBOLTS);

		bind(SkillActivity.SMITHING,
			AnimationID.HUMAN_SMITHING,
			AnimationID.HUMAN_SMITHING_IMCANDO_HAMMER,
			AnimationID.HUMAN_FURNACE);

		bind(SkillActivity.FISHING,
			AnimationID.INFERNALEEL_BREAK,
			AnimationID.INFERNALEEL_BREAK_IMCANDO,
			AnimationID.SNAKEBOSS_SLICEEEL,
			AnimationID.HUMAN_LARGENET,
			AnimationID.HUMAN_SMALLNET,
			AnimationID.HUMAN_FISH_ONSPOT,
			AnimationID.HUMAN_LOBSTER,
			AnimationID.HUMAN_HARPOON,
			AnimationID.HUMAN_HARPOON_BARBED,
			AnimationID.HUMAN_HARPOON_DRAGON,
			AnimationID.HUMAN_HARPOON_TRAILBLAZER_NO_INFERNAL,
			AnimationID.HUMAN_HARPOON_INFERNAL,
			AnimationID.HUMAN_HARPOON_CRYSTAL,
			AnimationID.HUMAN_HARPOON_LEAGUE_TRAILBLAZER,
			AnimationID.HUMAN_HARPOON_TRAILBLAZER_RELOADED_NO_INFERNAL,
			AnimationID.HUMAN_HARPOON_TRAILBLAZER,
			AnimationID.HUMAN_HARPOON_TRAILBLAZER_RELOADED,
			AnimationID.HUMAN_FISHING_CASTING,
			AnimationID.HUMAN_OCTOPUS_POT,
			AnimationID.BRUT_PLAYER_HAND_FISHING_END_BLANK,
			AnimationID.HUMAN_FISHING_CASTING_PEARL,
			AnimationID.HUMAN_FISHING_CASTING_PEARL_FLY,
			AnimationID.HUMAN_FISHING_CASTING_PEARL_BRUT,
			AnimationID.HUMAN_FISH_ONSPOT_PEARL,
			AnimationID.HUMAN_FISH_ONSPOT_PEARL_FLY,
			AnimationID.HUMAN_FISH_ONSPOT_PEARL_BRUT,
			AnimationID.HUMAN_FISHING_CASTING_PEARL_OILY,
			AnimationID.HUMAN_FISHING_ONSPOT_BRUT);

		bind(SkillActivity.MINING,
			AnimationID.HUMAN_MINING_BRONZE_PICKAXE,
			AnimationID.HUMAN_MINING_BRONZE_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_BRONZE_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_BRONZE,
			AnimationID.HUMAN_MINING_IRON_PICKAXE,
			AnimationID.HUMAN_MINING_IRON_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_IRON_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_IRON,
			AnimationID.HUMAN_MINING_STEEL_PICKAXE,
			AnimationID.HUMAN_MINING_STEEL_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_STEEL_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_STEEL,
			AnimationID.HUMAN_MINING_BLACK_PICKAXE,
			AnimationID.HUMAN_MINING_BLACK_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_BLACK_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_BLACK,
			AnimationID.HUMAN_MINING_MITHRIL_PICKAXE,
			AnimationID.HUMAN_MINING_MITHRIL_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_MITHRIL_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_MITHRIL,
			AnimationID.HUMAN_MINING_ADAMANT_PICKAXE,
			AnimationID.HUMAN_MINING_ADAMANT_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_ADAMANT_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_ADAMANT,
			AnimationID.HUMAN_MINING_RUNE_PICKAXE,
			AnimationID.HUMAN_MINING_RUNE_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_RUNE_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_RUNE,
			AnimationID.HUMAN_MINING_GILDED_PICKAXE,
			AnimationID.HUMAN_MINING_GILDED_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_GILDED_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_GILDED,
			AnimationID.HUMAN_MINING_DRAGON_PICKAXE,
			AnimationID.HUMAN_MINING_DRAGON_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_DRAGON_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_DRAGON,
			AnimationID.HUMAN_MINING_ZALCANO_PICKAXE,
			AnimationID.HUMAN_MINING_ZALCANO_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_ZALCANO_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_ZALCANO,
			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL_WALL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_TRAILBLAZER_NO_INFERNAL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL_WALL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL_NOREACHFORWARD,
			AnimationID.HUMAN_MINING_DRAGON_PICKAXE_PRETTY,
			AnimationID.HUMAN_MINING_DRAGON_PICKAXE_PRETTY_WALL,
			AnimationID.HUMAN_MINING_DRAGON_PICKAXE_PRETTY_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_PRETTY,
			AnimationID.HUMAN_MINING_INFERNAL_PICKAXE,
			AnimationID.HUMAN_MINING_INFERNAL_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_INFERNAL_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_INFERNAL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE,
			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_TRAILBLAZER,
			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE,
			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NOREACHFORWARD,
			AnimationID.HUMAN_MINING_3A_PICKAXE,
			AnimationID.HUMAN_MINING_3A_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_3A_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_3A,
			AnimationID.HUMAN_MINING_CRYSTAL_PICKAXE,
			AnimationID.HUMAN_MINING_CRYSTAL_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_CRYSTAL_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_CRYSTAL,
			AnimationID.HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE,
			AnimationID.HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_LEAGUE_TRAILBLAZER,
			AnimationID.HUMAN_MINING_ZALCANO_LEAGUE_TRAILBLAZER_PICKAXE,
			AnimationID.PICKAXE_POWER_SWING,
			AnimationID.ARCEUUS_CHISEL_ESSENCE,
			AnimationID.ARCEUUS_CHISEL_ESSENCEBLOCK);

		bind(SkillActivity.HERBLORE,
			AnimationID.HUMAN_HERBING_GRIND,
			AnimationID.HUMAN_HERBING_VIAL,
			AnimationID.HUMAN_SALAMANDER_TAR_GRIND,
			AnimationID.HUMAN_MACHINERY_ALCHEMY01_RETORT01_INTERACT01,
			AnimationID.HUMAN_MACHINERY_ALCHEMY01_ALEMBIC01_INTERACT01,
			AnimationID.HUMAN_MACHINERY_ALCHEMY01_AGITATOR01_INTERACT01,
			AnimationID.HUMAN_ALCHEMY01_MILL01_INTERACT01,
			AnimationID.HUMAN_HERBING_VIAL_RESTART,
			AnimationID.HUMAN_HERBING_GRIND_RESTART);

		bind(SkillActivity.MAGIC,
			AnimationID.HUMAN_CASTCHARGEORB,
			AnimationID.DREAM_PLAYER_MAKE_PLANK_SPELL,
			AnimationID.LUNAR_HUMAN_MAGIC_SUMMON1,
			AnimationID.POH_CREATE_MAGIC_TABLET,
			AnimationID.POH_CREATE_MAGIC_TABLET_WITHSTAFF,
			AnimationID.HUMAN_CAST_ENCHANTRING,
			AnimationID.HUMAN_ENCHANTAMULETLVL1,
			AnimationID.HUMAN_ENCHANTAMULETLVL2,
			AnimationID.HUMAN_ENCHANTAMULETLVL3,
			AnimationID.HUMAN_XBOW_ENCHANT_ARROWTIP);

		bind(SkillActivity.PRAYER,
			AnimationID.HUMAN_BONE_SACRIFICE,
			AnimationID.HUMAN_PRAY_BLESSED_BONE_SHARDS_01);

		bind(SkillActivity.FARMING,
			AnimationID.ULTRACOMPOST_MAKE,
			AnimationID.PICKING_MID,
			AnimationID.PICKING_LOW,
			AnimationID.PICKING_HIGH,
			AnimationID.FARMING_PICK_MUSHROOM,
			AnimationID.HUMAN_DIG);

		bind(SkillActivity.SAILING,
			AnimationID.SAILING_HUMAN_SALVAGE_HOOK_KANDARIN_1X3_IDLE01,
			AnimationID.SAILING_HUMAN_SALVAGE_HOOK_KANDARIN_2X5_IDLE01,
			AnimationID.SAILING_HUMAN_SALVAGE_HOOK_KANDARIN_3X8_IDLE01,
			AnimationID.SAILING_HUMAN_SALVAGE_HOOK_KANDARIN_1X3_INTERACT01,
			AnimationID.SAILING_HUMAN_SALVAGE_HOOK_KANDARIN_1X3_RESET01,
			AnimationID.SAILING_HUMAN_SALVAGE_HOOK_KANDARIN_2X5_RESET01,
			AnimationID.SAILING_HUMAN_SALVAGE_HOOK_KANDARIN_3X8_RESET01);

		bind(SkillActivity.CONSTRUCTION,
			AnimationID.HUMAN_POH_BUILD,
			AnimationID.HUMAN_POH_BUILD_FLOOR,
			AnimationID.HUMAN_POH_BUILD_WALL,
			AnimationID.HUMAN_POH_BUILD_DWH,
			AnimationID.HUMAN_POH_BUILD_IMCANDO_HAMMER,
			AnimationID.HUMAN_POH_BUILD_FLOOR_IMCANDO_HAMMER,
			AnimationID.HUMAN_POH_BUILD_WALL_IMCANDO_HAMMER,
			AnimationID.HUMAN_POH_BUILD_DWH_ORNAMENT,
			AnimationID.HUMAN_POH_BUILD_DWH_BH_CORRUPTED,
			AnimationID.HUMAN_POH_BUILD_ELDER_MAUL,
			AnimationID.HUMAN_POH_BUILD_ELDER_MAUL_ORNAMENT);

		bind(SkillActivity.RUNECRAFT,
			AnimationID.HUMAN_RUNECRAFT,
			AnimationID.HUMAN_RUNECRAFT_WALKMERGE,
			AnimationID.RUNECRAFTING);

		bind(SkillActivity.HUNTER,
			AnimationID.HUMAN_LAYTRAP,
			AnimationID.HUMAN_HUNTING_DISMANTLE_NET,
			AnimationID.HUMAN_BUTTERFLYNET_SWING);

		bind(SkillActivity.THIEVING,
			AnimationID.HUMAN_PICKPOCKET,
			AnimationID.VARLAMORE_THIEVING_SEARCH,
			AnimationID.HUMAN_SWIM_STEAL,
			AnimationID.HUMAN_SWIM_STEAL_FAIL,
			AnimationID.HUMAN_SWIM_STEAL_SUCCESS,
			AnimationID.HUMAN_SWIM_STEAL_FAIL_END);

		bind(SkillActivity.AGILITY,
			AnimationID.HUMAN_CLIMBING,
			AnimationID.HUMAN_CLIMBING_READY,
			AnimationID.HUMAN_CLIMBING_FALL,
			AnimationID.HUMAN_CLIMBING_DOWN,
			AnimationID.HUMAN_CLIMBING_LOOP,
			AnimationID.HUMAN_CLIMBING_DOWN_LOOP,
			AnimationID.HUMAN_ROPESWING,
			AnimationID.HUMAN_ROPESWING_LONG,
			AnimationID.HUMAN_WALK_LOGBALANCE,
			AnimationID.HUMAN_WALK_LOGBALANCE_READY,
			AnimationID.HUMAN_WALK_LOGBALANCE_STUMBLE,
			AnimationID.HUMAN_WALK_LOGBALANCE_LOOP,
			AnimationID.HUMAN_STEPPINGSTONEJUMP,
			AnimationID.HUMAN_JUMP_HURDLE,
			AnimationID.HUMAN_JUMP_STONES,
			AnimationID.HUMAN_LONGJUMP,
			AnimationID.HUMAN_SPOT_JUMP,
			AnimationID.HUMAN_THROWROPE,
			AnimationID.HUMAN_THROWROPE_UP,
			AnimationID.ROOFTOPS_POLE_VAULT,
			AnimationID.AGILITY_SHORTCUT_WALL_JUMP,
			AnimationID.AGILITY_SHORTCUT_WALL_JUMP_STATIC,
			AnimationID.AGILITY_SHORTCUT_WALL_JUMP2,
			AnimationID.AGILITY_SHORTCUT_WALL_JUMPDOWN,
			AnimationID.AGILITY_SHORTCUT_WALL_JUMPDOWN_STATIC,
			AnimationID.AGILITY_SHORTCUT_WALL_JUMPDOWN2,
			AnimationID.AGILITY_SHORTCUT_WALL_JUMPDOWN_NOREACHFORWARD,
			AnimationID.AGILITY_SHORTCUT_CRACK_ENTER,
			AnimationID.AGILITY_SHORTCUT_CRACK_LEAVE,
			AnimationID.AGILITY_SHORTCUT_CRACK_ENTER_LOOP,
			AnimationID.AGILITY_PYRAMID_LEDGE_ON_LEFT,
			AnimationID.AGILITY_PYRAMID_LEDGE_OFF_LEFT,
			AnimationID.AGILITY_PYRAMID_LEDGE_FALL_LEFT,
			AnimationID.AGILITY_PYRAMID_LEDGE_FALL_RIGHT,
			AnimationID.AGILITY_PYRAMID_LEDGE_ON_RIGHT,
			AnimationID.AGILITY_PYRAMID_LEDGE_OFF_RIGHT,
			AnimationID.AGILITY_PYRAMID_LEDGE_WALK_LEFT,
			AnimationID.AGILITY_PYRAMID_LEDGE_WALK_RIGHT,
			AnimationID.AGILITY_PYRAMID_SIDESTEP_FALL,
			AnimationID.AGILITY_PYRAMID_SIDESTEP_FALLL,
			AnimationID.AGILITY_PYRAMID_TOP_CLIMB,
			AnimationID.AGILITY_PYRAMID_TILT_FALL,
			AnimationID.AGILITY_PYRAMID_BLOCK_PUSH_1,
			AnimationID.AGILITY_PYRAMID_BLOCK_PUSH_2,
			AnimationID.AGILITY_PYRAMID_GAP_JUMP,
			AnimationID.AGILITY_PYRAMID_GAP_JUMP_FALL,
			AnimationID.AGILITY_PYRAMID_LOGFALL_R,
			AnimationID.AGILITY_PYRAMID_TILTING_FLOOR,
			AnimationID.VARLAMORE_WYRM_AGILITY_LONGJUMP,
			AnimationID.WYRM_AGILITY_ZIPLINE_WALK,
			AnimationID.WYRM_AGILITY_ZIPLINE_ON,
			AnimationID.WYRM_AGILITY_ZIPLINE_OFF,
			AnimationID.WYRM_AGILITY_ZIPLINE_READY,
			AnimationID.WYRM_AGILITY_LEDGE_WALK,
			AnimationID.WYRM_AGILITY_LEDGE_READY,
			AnimationID.WYRM_AGILITY_LEDGE_ON,
			AnimationID.WYRM_AGILITY_LEDGE_OFF);
	}

	private SkillActivities()
	{
	}

	static SkillActivity fromAnimation(int animationId)
	{
		return BY_ANIMATION.get(animationId);
	}

	/**
	 * XP that means "this skill is being trained". Prayer and magic are excluded
	 * because combat grants them too.
	 */
	static SkillActivity fromSkillXp(Skill skill)
	{
		switch (skill)
		{
			case WOODCUTTING:
				return SkillActivity.WOODCUTTING;
			case MINING:
				return SkillActivity.MINING;
			case FISHING:
				return SkillActivity.FISHING;
			case HUNTER:
				return SkillActivity.HUNTER;
			case AGILITY:
				return SkillActivity.AGILITY;
			case THIEVING:
				return SkillActivity.THIEVING;
			case FARMING:
				return SkillActivity.FARMING;
			case RUNECRAFT:
				return SkillActivity.RUNECRAFT;
			case CONSTRUCTION:
				return SkillActivity.CONSTRUCTION;
			case COOKING:
				return SkillActivity.COOKING;
			case FIREMAKING:
				return SkillActivity.FIREMAKING;
			case SMITHING:
				return SkillActivity.SMITHING;
			case FLETCHING:
				return SkillActivity.FLETCHING;
			case CRAFTING:
				return SkillActivity.CRAFTING;
			case HERBLORE:
				return SkillActivity.HERBLORE;
			case SAILING:
				return SkillActivity.SAILING;
			default:
				return null;
		}
	}

	private static void bind(SkillActivity activity, int... animationIds)
	{
		for (int animationId : animationIds)
		{
			SkillActivity previous = BY_ANIMATION.put(animationId, activity);
			if (previous != null && previous != activity)
			{
				throw new IllegalStateException("Animation " + animationId + " is both " + previous + " and " + activity);
			}
		}
	}
}
